# Generated by Django 5.1.2 on 2024-10-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
